### ISSUE TITLE
利用Xposed对Android的so黑盒利用 | Mario

### ISSUE THREAD

**Issue by StriveMario** [StriveMario/StriveMario.github.io#307]
https://strivemario.work/archives/46868.html 

 又是N久没有更新, 真的懒是能变成习惯的, 今天记录一下安卓里的so黑盒利用; 一般在逆向安卓的程序时, 重要的算法都在so里, 如果没有OLLVM还好, 如果一旦被VM了, 那么就只能退而其次想其他的解决办法, 那么开始吧

**Comment by niuguoqin** [comment]
在adb forward tcp:5597 tcp:5597操作前，虚拟机中安装完 app，点击打开后看到 logcat报错如下，查看设备发现设备 offline了，像您求助
09-29 02:21:29.028 624-636/system_process I/ActivityManager: Activity reported stop, but no longer stopping: ActivityRecord{a524a1 u0 com.virjar.hermes.hermesagent/.MainActivity t8}
09-29 02:21:29.041 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.040 [main] INFO  c.v.h.h.host.http.HttpServer - stop http server
09-29 02:21:29.041 1954-1954/? D/AndroidRuntime: Shutting down VM
09-29 02:21:29.043 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.042 [main] INFO  c.v.h.h.host.http.HttpServer - register http request handler
09-29 02:21:29.043 1908-2090/com.virjar.hermes.hermesagent I/NIO: Selector exception, shutting down
    com.koushikdutta.async.AsyncServer$AsyncSelectorException: java.nio.channels.ClosedSelectorException
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:769)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656)
        at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42)
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613)
     Caused by: java.nio.channels.ClosedSelectorException
        at java.nio.SelectorImpl.checkClosed(SelectorImpl.java:146)
        at java.nio.SelectorImpl.selectInternal(SelectorImpl.java:168)
        at java.nio.SelectorImpl.selectNow(SelectorImpl.java:164)
        at com.koushikdutta.async.SelectorWrapper.selectNow(SelectorWrapper.java:27)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:746)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656) 
        at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42) 
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613)

**Comment by StriveMario** [comment]
> @niuguoqin
> 在adb forward tcp:5597 tcp:5597操作前，虚拟机中安装完 app，点击打开后看到 logcat报错如下，查看设备发现设备 offline了，像您求助
> 09-29 02:21:29.028 624-636/system_process I/ActivityManager: Activity reported stop, but no longer stopping: ActivityRecord{a524a1 u0 com.virjar.hermes.hermesagent/.MainActivity t8}
> 09-29 02:21:29.041 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.040 [main] INFO  c.v.h.h.host.http.HttpServer - stop http server
> 09-29 02:21:29.041 1954-1954/? D/AndroidRuntime: Shutting down VM
> 09-29 02:21:29.043 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.042 [main] INFO  c.v.h.h.host.http.HttpServer - register http request handler
> 09-29 02:21:29.043 1908-2090/com.virjar.hermes.hermesagent I/NIO: Selector exception, shutting down
>     com.koushikdutta.async.AsyncServer$AsyncSelectorException: java.nio.channels.ClosedSelectorException
>         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:769)
>         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656)
>         at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42)
>         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613)
>      Caused by: java.nio.channels.ClosedSelectorException
>         at java.nio.SelectorImpl.checkClosed(SelectorImpl.java:146)
>         at java.nio.SelectorImpl.selectInternal(SelectorImpl.java:168)
>         at java.nio.SelectorImpl.selectNow(SelectorImpl.java:164)
>         at com.koushikdutta.async.SelectorWrapper.selectNow(SelectorWrapper.java:27)
>         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:746)
>         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656) 
>         at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42) 
>         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613) 

额, 设备离线的话, 你应该检查你的接口和连接线啊

**Comment by niuguoqin** [comment]
我是将 app install 在了 android studio中的虚拟设备中了> @StriveMario
> > @niuguoqin
> > 在adb forward tcp:5597 tcp:5597操作前，虚拟机中安装完 app，点击打开后看到 logcat报错如下，查看设备发现设备 offline了，像您求助
> > 09-29 02:21:29.028 624-636/system_process I/ActivityManager: Activity reported stop, but no longer stopping: ActivityRecord{a524a1 u0 com.virjar.hermes.hermesagent/.MainActivity t8}
> > 09-29 02:21:29.041 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.040 [main] INFO  c.v.h.h.host.http.HttpServer - stop http server
> > 09-29 02:21:29.041 1954-1954/? D/AndroidRuntime: Shutting down VM
> > 09-29 02:21:29.043 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.042 [main] INFO  c.v.h.h.host.http.HttpServer - register http request handler
> > 09-29 02:21:29.043 1908-2090/com.virjar.hermes.hermesagent I/NIO: Selector exception, shutting down
> >     com.koushikdutta.async.AsyncServer$AsyncSelectorException: java.nio.channels.ClosedSelectorException
> >         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:769)
> >         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656)
> >         at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42)
> >         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613)
> >      Caused by: java.nio.channels.ClosedSelectorException
> >         at java.nio.SelectorImpl.checkClosed(SelectorImpl.java:146)
> >         at java.nio.SelectorImpl.selectInternal(SelectorImpl.java:168)
> >         at java.nio.SelectorImpl.selectNow(SelectorImpl.java:164)
> >         at com.koushikdutta.async.SelectorWrapper.selectNow(SelectorWrapper.java:27)
> >         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:746)
> >         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656) 
> >         at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42) 
> >         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613) 
> 
> 额, 设备离线的话, 你应该检查你的接口和连接线啊

**Comment by StriveMario** [comment]
> @niuguoqin
> 我是将 app install 在了 genymotion的设备中了> @StriveMario
> > > @niuguoqin
> > > 在adb forward tcp:5597 tcp:5597操作前，虚拟机中安装完 app，点击打开后看到 logcat报错如下，查看设备发现设备 offline了，像您求助
> > > 09-29 02:21:29.028 624-636/system_process I/ActivityManager: Activity reported stop, but no longer stopping: ActivityRecord{a524a1 u0 com.virjar.hermes.hermesagent/.MainActivity t8}
> > > 09-29 02:21:29.041 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.040 [main] INFO  c.v.h.h.host.http.HttpServer - stop http server
> > > 09-29 02:21:29.041 1954-1954/? D/AndroidRuntime: Shutting down VM
> > > 09-29 02:21:29.043 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.042 [main] INFO  c.v.h.h.host.http.HttpServer - register http request handler
> > > 09-29 02:21:29.043 1908-2090/com.virjar.hermes.hermesagent I/NIO: Selector exception, shutting down
> > >     com.koushikdutta.async.AsyncServer$AsyncSelectorException: java.nio.channels.ClosedSelectorException
> > >         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:769)
> > >         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656)
> > >         at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42)
> > >         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613)
> > >      Caused by: java.nio.channels.ClosedSelectorException
> > >         at java.nio.SelectorImpl.checkClosed(SelectorImpl.java:146)
> > >         at java.nio.SelectorImpl.selectInternal(SelectorImpl.java:168)
> > >         at java.nio.SelectorImpl.selectNow(SelectorImpl.java:164)
> > >         at com.koushikdutta.async.SelectorWrapper.selectNow(SelectorWrapper.java:27)
> > >         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:746)
> > >         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656) 
> > >         at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42) 
> > >         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613) 
> > 
> > 额, 设备离线的话, 你应该检查你的接口和连接线啊
> 
> 

这个原因我不是很清楚, 我记得当时我是用的逍遥模拟器测试的, 你可以尝试一下

**Comment by niuguoqin** [comment]
您好，抱歉打扰了，您提到的那个模拟器没有 mac版本的。我又重新试了好几次，发现每次 Superuser 授权完root权限给Hermes后，就导致设备离线了(有一次我是一次一次授权的，重定向完端口可以达到文章中的效果，但是一次性授权的话就会导致设备离线，不清楚是不是模拟器的原因)@StriveMario
> > @niuguoqin
> > 我是将 app install 在了 genymotion的设备中了> @StriveMario
> > > > @niuguoqin
> > > > 在adb forward tcp:5597 tcp:5597操作前，虚拟机中安装完 app，点击打开后看到 logcat报错如下，查看设备发现设备 offline了，像您求助
> > > > 09-29 02:21:29.028 624-636/system_process I/ActivityManager: Activity reported stop, but no longer stopping: ActivityRecord{a524a1 u0 com.virjar.hermes.hermesagent/.MainActivity t8}
> > > > 09-29 02:21:29.041 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.040 [main] INFO  c.v.h.h.host.http.HttpServer - stop http server
> > > > 09-29 02:21:29.041 1954-1954/? D/AndroidRuntime: Shutting down VM
> > > > 09-29 02:21:29.043 1908-1908/com.virjar.hermes.hermesagent I/com.virjar.hermes.hermesagent.host.http.HttpServer: 2019-09-29 02:21:29.042 [main] INFO  c.v.h.h.host.http.HttpServer - register http request handler
> > > > 09-29 02:21:29.043 1908-2090/com.virjar.hermes.hermesagent I/NIO: Selector exception, shutting down
> > > >     com.koushikdutta.async.AsyncServer$AsyncSelectorException: java.nio.channels.ClosedSelectorException
> > > >         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:769)
> > > >         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656)
> > > >         at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42)
> > > >         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613)
> > > >      Caused by: java.nio.channels.ClosedSelectorException
> > > >         at java.nio.SelectorImpl.checkClosed(SelectorImpl.java:146)
> > > >         at java.nio.SelectorImpl.selectInternal(SelectorImpl.java:168)
> > > >         at java.nio.SelectorImpl.selectNow(SelectorImpl.java:164)
> > > >         at com.koushikdutta.async.SelectorWrapper.selectNow(SelectorWrapper.java:27)
> > > >         at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:746)
> > > >         at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:656) 
> > > >         at com.koushikdutta.async.AsyncServer.access$900(AsyncServer.java:42) 
> > > >         at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:613) 
> > > 
> > > 额, 设备离线的话, 你应该检查你的接口和连接线啊
> > 
> > 
> 
> 这个原因我不是很清楚, 我记得当时我是用的逍遥模拟器测试的, 你可以尝试一下
